### ISSUE TITLE
Need to fill out the "tree" idea and get a graphic in here...

### ISSUE THREAD

**Issue by sgharms** [learn-co-curriculum/cli-essentials-bash-navigation#4]
We use "tree" several times, can we get a graphic in here of a unix tree (i thought you and I found one once? did it go somewhere?). I think it's worth taking a SHORT dog-leg to the side to explain the tree metaphor b/c we use it repeatedly.

**Comment by sgharms** [comment]
cc: @drakeltheryuujin

**Comment by jenmyers** [comment]
Added a note and image to the README.
